Lesson2
fred18811/geekshop-server pull request #2
Opened 2021-06-28 12:26 UTC by fred18811

did all tasks

2021-06-28 16:16 UTC, Vokler requested changes

2021-06-28 16:16 UTC, Vokler commented on products/fixtures/goods.json
> +  "title": "GeekShop - Каталог",
В данном файле должен находиться только список продуктов, а остальное формировать в context в самом контроллере

2021-06-28 19:21 UTC, fred18811 commented on products/fixtures/goods.json
> +  "title": "GeekShop - Каталог",
Исправил, сделал в json только продукты

2021-06-29 06:32 UTC, Vokler approved these changes

2021-06-29 06:33 UTC, merged