Lesson3
fred18811/geekshop-server pull request #3
Opened 2021-07-01 08:05 UTC by fred18811

Сделал все задания по списку!

2021-07-02 14:17 UTC, Vokler requested changes

2021-07-02 14:17 UTC, Vokler commented on products/views.py
> +    context['products'] = Product.objects.all()
Добавьте сюда еще работу с категориями

2021-07-02 17:53 UTC, fred18811 commented on products/views.py
> +    context['products'] = Product.objects.all()
Добавил во views работу скатегориями

2021-07-04 13:48 UTC, Vokler approved these changes

2021-07-04 13:48 UTC, merged